import type { Metadata } from "next";
import "./globals.scss";
import { Header } from "@/src/components/header";
import { ApolloWrapper } from "@/src/lib/apollo-provider";
import { roboto } from "@/fonts";

export const metadata: Metadata = {
  title: "Revieweet!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={roboto.className}>
        <ApolloWrapper>
          <Header />
          {children}
        </ApolloWrapper>
      </body>
    </html>
  );
}