import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.scss";
import { Header } from "@/src/components/header";
import { ApolloWrapper } from "@/src/lib/apollo-provider";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ 
  subsets: ["latin"],
  weight: ["400", "700"]
});

export const metadata: Metadata = {
  title: "Revieweet!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ApolloWrapper>
          <Header />
          {children}
        </ApolloWrapper>
      </body>
    </html>
  );
}